-- Domia Real Estate - Initial Database Schema
-- Run this script in your Supabase SQL Editor

-- 1. Create Properties Table
CREATE TABLE public.properties (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Basic Info
  title TEXT NOT NULL,
  description TEXT,
  ai_description TEXT, -- Generated by AI
  price NUMERIC NOT NULL,
  currency TEXT DEFAULT 'PEN', -- 'PEN' or 'USD'
  type TEXT NOT NULL, -- 'sale' or 'rent'
  property_type TEXT NOT NULL, -- 'apartment', 'house', 'commercial', etc.
  
  -- Location
  address TEXT NOT NULL,
  district TEXT NOT NULL,
  city TEXT DEFAULT 'Lima',
  lat NUMERIC(10, 8),
  lng NUMERIC(11, 8),
  
  -- Characteristics
  area_sqm NUMERIC NOT NULL,
  bedrooms INTEGER DEFAULT 0,
  bathrooms NUMERIC DEFAULT 0,
  parking_spots INTEGER DEFAULT 0,
  
  -- Flags
  is_verified BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  
  -- Ownership
  owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

-- 2. Create Property Images Table
CREATE TABLE public.property_images (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  property_id UUID REFERENCES public.properties(id) ON DELETE CASCADE NOT NULL,
  url TEXT NOT NULL,
  is_main BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Set up Row Level Security (RLS)
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.property_images ENABLE ROW LEVEL SECURITY;

-- Policies for Properties
-- Anyone can read active properties
CREATE POLICY "Public profiles are viewable by everyone." 
ON public.properties FOR SELECT USING (is_active = TRUE);

-- Only authenticated users can insert properties
CREATE POLICY "Users can insert their own properties." 
ON public.properties FOR INSERT WITH CHECK (auth.uid() = owner_id);

-- Owners can edit their own properties
CREATE POLICY "Users can update own properties."
ON public.properties FOR UPDATE USING (auth.uid() = owner_id);

-- Policies for Images
-- Anyone can view images of active properties
CREATE POLICY "Images viewable by everyone."
ON public.property_images FOR SELECT USING (TRUE);

-- Owners can upload images
CREATE POLICY "Owners can insert images."
ON public.property_images FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM public.properties WHERE id = property_id AND owner_id = auth.uid())
);
